const ENV_CONFIGURATIONS = {
    API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
    SERVICE_PROVIDER: process.env.REACT_APP_SERVICE_PROVIDER,
    API_BASE_SOCKET_DOMAIN: process.env.REACT_APP_API_BASE_SOCKET_DOMAIN,
    FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGE_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGE_SENDER_ID,
    FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,

    GOOGLE_MAPS_API_KEY: process.env.REACT_APP_MAPS_API_KEY,
    GOOGLE_MAPS_MAP_ID: process.env.REACT_APP_MAP_ID,
    REACT_APP_STRIPE_API_KEY: process.env.REACT_APP_STRIPE_API_KEY,
    SERVICE_PROVIDER_URL: process.env.REACT_APP_KIDSPLAN_SERVICE_PROVIDER_URL,
}

export const CONFIGURATIONS = ENV_CONFIGURATIONS;
